### ISSUE TITLE
Console Spam when checking Universal Coins Inventory

### ISSUE THREAD

**Issue by jermangarc** [dries007/HoloInventory#12]
Hello, I get a ton of console spam when using Universal Coins' Vending Block. This mod is all about selling items in-game using gold coins. When I use the Vending Block Machine and insert item into item box, I get the following spam (http://pastebin.com/s9qVE0sr) on the server console to the point where we all get timed out. It does not crash the server nor the client, just console spam timeouts. Thanks for your help.

https://dl.dropboxusercontent.com/u/72156241/2015-06-11_20.15.16.png
Forge 10.13.3.1408
HoloInventory-1.7.10-1.9.0.108
UniversalCoins-1.7.10-1.6.8 https://github.com/notabadminer/UniversalCoinsMod

**Comment by notabadminer** [comment]
This issue was due to bad programming on my end. Fixed with the 1.7.10-1.6.12 release.

**Comment by dries007** [comment]
Oh, that is nice to read. What went wrong?
