### ISSUE TITLE
Included Storage Drawers API causing conflict

### ISSUE THREAD

**Issue by jaquadro** [dries007/HoloInventory#13]
Hi, I'm the Storage Drawers author.  Your mod is currently packaging a copy of Storage Drawers API, which is conflicting with the latest version of Storage Drawers since I made a couple additions to the API (unrelated to your current usage).

It's important that multiple mods do not distribute a copy of an API.  You can use the build.gradle and integration/ source files in Storage Drawers as a reference if you are unsure how to conditionally depend on the availability of the API (https://github.com/jaquadro/StorageDrawers), or feel free to ask me any questions about it.

**Comment by dries007** [comment]
Facepalm.
I meant to do the FML API thing after making sure what I did worked, but completely forgot about it.
Sorry for the inconvenience.
