### ISSUE TITLE
get kicked after using /dimensiontp

### ISSUE THREAD

**Issue by Dream-Master** [dries007/HoloInventory#17]
if i using the command /dimensiontp (far Galacticraft and galaxy Sapce) i get kicket in sp and return to the main menu. After this the save game is unplayable because i get kickt again.

This is in my fml log:
https://gist.github.com/Dream-Master/5c70c0a046b84593a645

it not crash the game only return to menu.

**Comment by dries007** [comment]
Can you verify that its fixed with the new build? https://jenkins.dries007.net/job/HoloInventory/122/

**Comment by Dream-Master** [comment]
Yes sure. I let you know.

**Comment by Dream-Master** [comment]
Yes works for me no more crash when i am using /dimensiontp now. Thanks
