### ISSUE TITLE
Update checker error

### ISSUE THREAD

**Issue by Dream-Master** [dries007/HoloInventory#20]
When start a new Game i get tjis.

https://www.dropbox.com/s/h6zyr2qa462gx9o/Screenshot%202016-05-18%2009.27.13.png?dl=0

Fml Log:

https://gist.github.com/Dream-Master/1c020d94e8bc25833650f91401c32178

**Comment by dries007** [comment]
Thanks, I can fix after Friday.

**Comment by dries007** [comment]
fixed it
