### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by P3t3rU5** [dries007/HoloInventory#21]
Possibly compatibility problems with fastcraft?

http://pastebin.com/vL1f4iPv

**Comment by dries007** [comment]
Can you reproduce without fastcraft? If not, please report to Player and see what he sais. He messes with way to much, and since fastcraft is coded specifically to prevent others from understanding what it does, I cannot offer assistance in making them work together.

**Comment by P3t3rU5** [comment]
Thank you for the fast response, I'll try to contact him.

**Comment by dries007** [comment]
First try to make sure it only happens with fastcraft, and not also without! (Look at the same block)
