### ISSUE TITLE
1.8 Support

### ISSUE THREAD

**Issue by Rono97** [dries007/HoloInventory#24]
Hi, I was wondering if you planned on creating a 1.8 version, You have 1.10, 1.9, 1.8.9, 1.7.10 but skipped 1.8, I love the idea behind the plugin, however, 1.8 would benefit a lot of people.

**Comment by dries007** [comment]
I think someone made a port for 1.8, I'll try and find it. If not I don't
think I'll port it, but I'll contact someone who may.

Op 7 nov. 2016 1:35 a.m. schreef "Rono" <notifications@github.com>:

**Comment by Rono97** [comment]
Alright, Thank You <3

**Comment by dries007** [comment]
Here you go: https://minecraft.curseforge.com/projects/holoinventory/files/2342634
Its a port of the 1.8.9 build, unfortunately I don't have the time to test it properly. Be sure to report any issues you encounter!
