### ISSUE TITLE
Conflict with Applied Energistics

### ISSUE THREAD

**Issue by Xiaminou** [dries007/HoloInventory#25]
#### Description
Shift-clicking storage cells in the I/O Port causes a fatal error from time to time.
23:58:28: [fml-server-latest.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/623235/fml-server-latest.txt)

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2668

#### Environment

- Mods: [list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/623239/list.txt)
- Minecraft Version: 1.10.2
- AE2 Version: alpha 7
- Forge Version: 2135

**Comment by dries007** [comment]
Looking into it, but it's quite a strange one. Has it only ever happend with the IO ports?

**Comment by Xiaminou** [comment]
As far as I can remember, yes.

**Comment by dries007** [comment]
I'll do my best, but I can't promice a definitive fix. ConcurrentModificationException means its a threading problem, and as far as I know, in the context where it happens, it shouldn't be possible. Unless AE does something weird (they probably shouldn't)

**Comment by Xiaminou** [comment]
Well the I/O Port exports items from the storage cells to the network as soon as it enters it so it might have something to do with that, just guessing.

**Comment by dries007** [comment]
Would you mind trying and reporting back?
Get the build here: https://jenkins.dries007.net/job/HoloInventory/140/
If you don't have issues anymore, I'll upload it to curse.

**Comment by Xiaminou** [comment]
still happening: [fml-server-latest.txt](https://github.com/dries007/HoloInventory/files/632222/fml-server-latest.txt)

**Comment by dries007** [comment]
That log still mentions build 139. Please try 140.

**Comment by Xiaminou** [comment]
Oh right, derp, I changed it on the client and forgot to change on the server.

**Comment by Xiaminou** [comment]
No crash this time, after 2 tries. Looks fixed, thank you.

**Comment by dries007** [comment]
OK, if it does happen again, feel free to reopen.
