### ISSUE TITLE
Conflict with Immersive Engineering's Arc Furnace

### ISSUE THREAD

**Issue by Xiaminou** [dries007/HoloInventory#26]
After the blocks formed the Arc Furnace it kicked me out of the server and keeps doing it whenever I rejoined.

Server log: [fml-server-3.txt](https://github.com/dries007/HoloInventory/files/637030/fml-server-3.txt)

**Comment by dries007** [comment]
Will look at it when I have some time.

**Comment by dries007** [comment]
Can you try and use [build 141](https://jenkins.dries007.net/job/HoloInventory/141/)?
If it spams some log lines along the lines of "Error: Block at <coords & info> returned null after indicating the capability is available.", post those here.
They'll hopefully tell me who/what to yell at.

**Comment by Xiaminou** [comment]
Looks like it's fixed, thanks.

**Comment by dries007** [comment]
Alright! Will be uploading this build to Curse today.
