### ISSUE TITLE
2.0.2 vs 2.0.3

### ISSUE THREAD

**Issue by C0rn3j** [dries007/HoloInventory#27]
https://minecraft.curseforge.com/projects/holoinventory/files

The newest uploaded file is 2.0.2, but the older files are marked as 2.0.3, which is newer?

**Comment by Claycorp** [comment]
Whatever has the highest last number is newset. 
2.0.2.141 is newer than 2.0.3.139
I'll also fix the numbers.

**Comment by C0rn3j** [comment]
Thanks for fixing it, now it makes sense!
