### ISSUE TITLE
Impossible Installation

### ISSUE THREAD

**Issue by Floyedtheburger** [dries007/HoloInventory#29]
Hello im floyedtheburger, and i cant seem to install your mod! There are no installation tutorials and i can only pray you keep a close eye on this mod. PLEASE give the EXACT way you install this mod! D:

**Comment by dries007** [comment]
You install forge, then you put the download from CurseForge in the mods folder.
You can also use Curse's launcher, and add the mod via that, it's generally easier. There are also lots of tutorials about that.

**Comment by Floyedtheburger** [comment]
DUDE THAT WAS FAST! ⭕️ 
GOD BLESS YOU

**Comment by Floyedtheburger** [comment]
Also can you give link towards tutorials?

**Comment by dries007** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mods-discussion/2593037-how-to-start-playing-modded-minecraft-curse-voice
