### ISSUE TITLE
Tuttorial links

### ISSUE THREAD

**Issue by Floyedtheburger** [dries007/HoloInventory#30]
SORRY i have to do this, but you closed the last one so fast i dint get a chance to reply! I m just seeking the tutorials you spoke of, where are they? i cant find them D:

**Comment by dries007** [comment]
You can still reply to the original one, its just not an actual issue so I closed it.

**Comment by Floyedtheburger** [comment]
Sorry for this trouble. Im just NOT used to this site. Deepest apologies..
