### ISSUE TITLE
[1.11.2-2.0.2.143] crash while sneaking at Fluid Generator from Neotech.

### ISSUE THREAD

**Issue by kreezxil** [dries007/HoloInventory#33]
https://pastebin.com/VJnnwH7E

1.  placed fluid generator
1.  held sneak while looking at it

Expected not to crash, really wasn't expecting to see a hologram of rf energy either.

**Comment by dries007** [comment]
It's because [this](https://github.com/TeamBR-Modding/NeoTech/blob/master/src/main/java/com/teambrmodding/neotech/common/tiles/AbstractMachine.java#L456-L474) function is not capable of handling the `null` as a direction. (It's used as the 'internal' direction by many things, including HoloInventory.

**Comment by kreezxil** [comment]
is it possible to ban the entire mod from the holoinventory?

**Comment by kreezxil** [comment]
for instance like

S:banned <
neotech:*
>

**Comment by kreezxil** [comment]
Apparently banning all of the items provided by neotech didn't help, as the client crashed with the same report. I saw what you posted to them earlier, I'm hoping you will tell me that I did the config wrong.

```
# Configuration file

holoinventory {
    S:banned <
			neotech:electricfurnace
			neotech:electriccrusher
			neotech:furnacegenerator
			neotech:fluidgenerator
			neotech:electriccrucible
			neotech:electricsolidifier
			neotech:alloyer
			neotech:centrifuge
			neotech:treefarm
			neotech:basicenergystorage
			neotech:advancedenergystorage
			neotech:eliteenergystorage
			neotech:creativeenergystorage
			neotech:basictank
			neotech:advancedtank
			neotech:elitetank
			neotech:creativetank
			neotech:voidtank
			neotech:solarpanelt1
			neotech:solarpanelt2
			neotech:solarpanelt3
     >

    # Show on sneak, bypasses other keyboard settings.
    B:showOnSneak=true

    # Show on sprint, bypasses other keyboard settings.
    B:showOnSprint=true
}


```

**Comment by dries007** [comment]
Try Banning it on the server? The ban system was never meant to mitigate
crashes...

Op 13 apr. 2017 12:24 a.m. schreef "kreezxil" <notifications@github.com>:

**Comment by kreezxil** [comment]
I put rusty on both the server and the client
