### ISSUE TITLE
Ability to use on server

### ISSUE THREAD

**Issue by iiPostMaster** [dries007/HoloInventory#34]
My problem is, I need this to work in servers without the server having it. I'm an op on a friend's server, and he wants only the ops to use it. He doesn't want any version of the mod installed on his server for whatever reason, and he won't budge on that. Some memory issues with his server and not being able to add a mod without removing some other mods or plugins? I'm not entirely sure of his problem. He originally spoke Russian and is still learning English, he plainly said "No. Not enough storage available. No install, period."

Anyways, do you have a release specifically for 1.12 that works without the server having it? And could you possibly release a second mod that works without the server having it, with a warning that servers could ban you?

Thank you very much for taking the time to read and respond to my issue, I look forward to your answer.

**Comment by Claycorp** [comment]
It can't work only on the client as it needs the get information from the server to update the HUD when you look at an inventory.

I'm not totally sure why you want to limit it OPs only as the person can just open the inventory to see in it, but spectator should let you achieve the closest thing to this without adding mods. Other than that I doubt anything exists client side only for whatever you are attempting to do.

**Comment by dries007** [comment]
As clay said, The server doesn't send the required data to the client, that's why you need it on the server.
